<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'first_name' => 'Violeta',
                'middle_name' => null,
                'last_name' => 'Taneva',
                'username' => 'violeta',
                'email' => 'violeta@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Bulgaria',
                'is_admin' => true,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-08 20:34:21',
            ],
            [
                'first_name' => 'Matea',
                'middle_name' => null,
                'last_name' => 'Karst',
                'username' => 'matea',
                'email' => 'matea@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Croatia',
                'is_admin' => true,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-09 08:45:27',
            ],
            [
                'first_name' => 'Ani',
                'middle_name' => 'Chhoying',
                'last_name' => 'Dolma',
                'username' => 'ani',
                'email' => 'ani@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Nepal',
                'is_admin' => true,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-10 08:45:27',
            ],
            [
                'first_name' => 'Miguel',
                'middle_name' => 'Ángel',
                'last_name' => 'Rodríguez',
                'username' => 'miguel',
                'email' => 'miguel@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Spain',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-15 08:45:27',
            ],
            [
                'first_name' => 'Luca',
                'middle_name' => 'Alessandro',
                'last_name' => 'Rossi',
                'username' => 'luca',
                'email' => 'luca@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Italy',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-20 17:23:48',
            ],
            [
                'first_name' => 'Sakura',
                'middle_name' => 'Hanako',
                'last_name' => 'Yamamoto',
                'username' => 'sakura',
                'email' => 'sakura@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Japan',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-22 13:05:14',
            ],
            [
                'first_name' => 'Jorge',
                'middle_name' => null,
                'last_name' => 'Martínez',
                'username' => 'jorge',
                'email' => 'jorge@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Mexico',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-25 09:18:22',
            ],
            [
                'first_name' => 'Maria',
                'middle_name' => 'Isabel',
                'last_name' => 'Fernández',
                'username' => 'maria',
                'email' => 'maria@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Spain',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-27 16:45:55',
            ],
            [
                'first_name' => 'Chen',
                'middle_name' => 'Yuan',
                'last_name' => 'Li',
                'username' => 'chen',
                'email' => 'chen@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'China',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-10-30 11:32:40',
            ],
            [
                'first_name' => 'Giulia',
                'middle_name' => null,
                'last_name' => 'Bianchi',
                'username' => 'giulia',
                'email' => 'giulia@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Italy',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-11-02 15:22:13',
            ],
            [
                'first_name' => 'Ravi',
                'middle_name' => 'Kumar',
                'last_name' => 'Patel',
                'username' => 'ravi',
                'email' => 'ravi@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'India',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-11-05 10:19:52',
            ],
            [
                'first_name' => 'Elena',
                'middle_name' => 'María',
                'last_name' => 'García',
                'username' => 'elena',
                'email' => 'elena@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Spain',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-11-08 18:55:39',
            ],
            [
                'first_name' => 'Tenzin',
                'middle_name' => null,
                'last_name' => 'Dorji',
                'username' => 'tenzin',
                'email' => 'tenzin@lingua.com',
                'password' => Hash::make('password'),
                'country' => 'Bhutan',
                'is_admin' => false,
                'is_banned' => false,
                'photo' => 'avatars/default.png',
                'created_on' => '2023-11-10 14:22:18',
            ],
        ]);
    }
}
